version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      npm-dev-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
